spring:
  data:
    mongodb:
      uri: mongodb+srv://vajithc:Navigarion123@cluster0.cui4edz.mongodb.net/TREINETIC?retryWrites=true&w=majority

#spring.data.mongodb.uri=mongodb+srv://vajithc:Navigarion123@cluster0.cui4edz.mongodb.net/TREINETIC?retryWrites=true&w=majority